## Домашнее задание по теме урока: Алгоритм линейной регрессии. Градиентный спуск.

* [1. Подберите скорость обучения (alpha) и количество итераций:](#one)
* [2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее](#two)
* [3 Задача](#three)


In [151]:
import numpy as np
import matplotlib.pyplot as plt

In [152]:
#Пространство признаков для объекта (стаж репетиторы)
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])

In [153]:
# Целевая переменная (средний балл ЕГЭ)
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [154]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

def calc_mae(y, y_pred):
    err = np.mean(np.abs(y - y_pred))
    return err

#### 1. Подберите скорость обучения (alpha) и количество итераций <a class="anchor" id="one"></a>

In [155]:
n = X.shape[1]
n

10

In [156]:
n_iterations = 1600 # 1600 итераций при шаге 0.01
alpha = 0.01
w_list=[]
errors= []
W = np.random.randn(2)

for iteration in range(n_iterations):
    gradients = 2/n * X.dot(W.dot(X) - y)
    W = W - alpha * gradients
    err = calc_mse(y, W.dot(X))
    w_list.append(W)
    errors.append(err)
    
w_list[-1], errors[-1]

(array([47.23214037,  3.91071475]), 45.93750000000332)

#### 2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее <a class="anchor" id="two"></a>

In [157]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.01)

In [158]:
n = X.shape[1]
alpha = 1e-2
W = np.array([1, 0.5])

for i in range(1400):
    #y_pred = np.dot(W, X)
    err = calc_mse(y, W.dot(X))
    '''for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
    W -= (alpha * (2/n * (X.dot(W.dot(X) - y)))) # исправлено
    if i % 100 == 0:
        print(i, W, err)

0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.74418155] 175.19445858001842
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666785
400 [46.56511152  4.03388672] 46.181755648107604
500 [46.99760587  3.95402334] 45.96769776787538
600 [47.14967657  3.92594232] 45.941233404700036
700 [47.20314662  3.91606866] 45.93796156758051
800 [47.2219474   3.91259695] 45.93755706443538
900 [47.228558    3.91137626] 45.937507054979434
1000 [47.23088237  3.91094704] 45.937500872219864
1100 [47.23169965  3.91079613] 45.93750010783411
1200 [47.23198702  3.91074306] 45.93750001333172
1300 [47.23208806  3.9107244 ] 45.93750000164824


#### *3 (дополнительная): вместо того, чтобы задавать количество итераций, задайте условие остановки алгоритма - когда ошибка за итерацию начинает изменяться ниже определенного порога (упрощенный аналог параметра tol в линейной регрессии в sklearn).<a class="anchor" id="three"></a>

In [159]:
len(y)

10

In [160]:
w_list = [] # список векторов весов после каждой итерации
errors = [] # список значений ошибок после каждой итерации
eta = 0.01 # шаг градиентного спуска
max_iter = 10000 # максимальное число итераций
min_weight_dist = 1e-8 # критерий сходимости (разница весов, при которой алгоритм останавливается)
weight_dist = np.inf # зададим начальную разницу весов большим числом
iter_num = 0 # счетчик итераций
w = np.random.randn(2)
w_list, errors, w

([], [], array([-0.79356688,  1.73846946]))

In [161]:
X

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  2,  1,  3,  0,  5, 10,  1,  2]])

In [162]:
# ход градиентного спуска
while weight_dist > min_weight_dist and iter_num < max_iter:
    new_w = w - 2 * eta * X.dot(X.T.dot(w) - y)/len(y)
    weight_dist = np.linalg.norm(new_w - w, ord=2)
    
    w_list.append(new_w)
    errors.append(calc_mse(y, W.dot(X)))
    
    iter_num += 1
    w = new_w
    
w_list = np.array(w_list)

print(f'В случае использования градиентного спуска функционал ошибки составляет {round(errors[-1], 4)}')
print()
print(iter_num, 'итераций необходимо до достижения сходимости')

В случае использования градиентного спуска функционал ошибки составляет 45.9375

1695 итераций необходимо до достижения сходимости
